/*
 * dma_channel.h
 *
 *  Created on: 20 feb. 2025
 *      Author: Ludo
 */

#ifndef __DMA_CHANNEL_H__
#define __DMA_CHANNEL_H__

#include "dma.h"

#define DMA_INSTANCE_ACV_SAMPLING   DMA_INSTANCE_DMA1
#define DMA_CHANNEL_ACV_SAMPLING    DMA_CHANNEL_1

#define DMA_INSTANCE_ACI_SAMPLING   DMA_INSTANCE_DMA1
#define DMA_CHANNEL_ACI_SAMPLING    DMA_CHANNEL_2

#define DMA_INSTANCE_ACV_FREQUENCY  DMA_INSTANCE_DMA1
#define DMA_CHANNEL_ACV_FREQUENCY   DMA_CHANNEL_3

#define DMA_INSTANCE_TIC            DMA_INSTANCE_DMA1
#define DMA_CHANNEL_TIC             DMA_CHANNEL_4

#endif /* __DMA_CHANNEL_H__ */
